import classes
import subprogrames

if __name__ == "__main__":
    graf_test1 = classes.Graf(4)
    graf_test1.afegir_aresta(0, 1, 1)
    graf_test1.afegir_aresta(2, 1, 1)
    graf_test1.afegir_aresta(3, 1, 1)
    graf_test1.afegir_aresta(1, 3, 1)
    graf_test1.afegir_aresta(3, 3, 1)

    graf_test1.afegir_aresta(1, 0, 1)
    graf_test1.afegir_aresta(1, 2, 1)

    # graf_test1.mostrar_graf()
    # print(graf_test1.profunditat(2))
    # print(f"Graf 1: {subprogrames.es_connex(graf_test1)}")
    # print(graf_test1.prim())

    graf_test2 = classes.Graf(4)
    graf_test2.afegir_aresta(0, 1, 1)
    graf_test2.afegir_aresta(1, 0, 1)
    graf_test2.afegir_aresta(1, 2, 1)
    graf_test2.afegir_aresta(2, 1, 1)
    graf_test2.afegir_aresta(0, 2, 1)
    graf_test2.afegir_aresta(2, 0, 1)
    graf_test2.afegir_aresta(2, 3, 1)
    graf_test2.afegir_aresta(3, 2, 1)

    # graf_test2.mostrar_graf()
    # print(f"Graf 2: {subprogrames.es_connex(graf_test2)}")
    # print(graf_test2.prim())

    graf_test4 = classes.Graf(5)
    graf_test4.afegir_aresta(0, 1, 1)
    # graf_test4.afegir_aresta(1, 0, 1)
    graf_test4.afegir_aresta(0, 2, 3)
    # graf_test4.afegir_aresta(2, 0, 3)
    graf_test4.afegir_aresta(0, 3, 2)
    # graf_test4.afegir_aresta(3, 0, 2)
    graf_test4.afegir_aresta(1, 3, 2)
    # graf_test4.afegir_aresta(3, 1, 2)
    graf_test4.afegir_aresta(3, 2, 1)
    # graf_test4.afegir_aresta(2, 3, 1)
    graf_test4.afegir_aresta(2, 4, 4)
    # graf_test4.afegir_aresta(4, 2, 4)
    graf_test4.afegir_aresta(3, 4, 3)
    # graf_test4.afegir_aresta(4, 3, 3)
    graf_test4.afegir_aresta(4, 1, 4)
    # graf_test4.afegir_aresta(1, 4, 4)

    print(f"Graf 4: {graf_test4.prim()}")
    # print(subprogrames.es_connex(graf_test4))

    graf_test3 = classes.Graf(6)
    graf_test3.afegir_aresta(0, 2, 1)
    # graf_test3.afegir_aresta(2, 0, 1)
    graf_test3.afegir_aresta(2, 1, 1)
    # graf_test3.afegir_aresta(1, 2, 1)
    graf_test3.afegir_aresta(2, 3, 4)
    # graf_test3.afegir_aresta(3, 2, 4)
    graf_test3.afegir_aresta(1, 3, 3)
    # graf_test3.afegir_aresta(3, 1, 3)
    graf_test3.afegir_aresta(3, 5, 2)
    # graf_test3.afegir_aresta(5, 3, 2)
    graf_test3.afegir_aresta(3, 4, 5)
    # graf_test3.afegir_aresta(4, 3, 5)
    graf_test3.afegir_aresta(5, 4, 3)
    # graf_test3.afegir_aresta(4, 5, 3)

    print(f"Graf 3: {graf_test3.prim()}")
    # graf_test3.mostrar_graf()
    # print(subprogrames.es_connex(graf_test3))
